export type Status = "healthy" | "warning" | "critical";

export interface Component {
  id: string;
  name: string;
  status: Status;
  function: string;
  description: string;
  principle: string;
  material: string;
  dimensions: string;
  manufacturer: string;
  lifeExpectancy: string;
  failureModes: string[];
  symptoms: string[];
  causes: string[];
  inspection: { checklist: string[]; tools: string[]; tolerances: string };
  maintenance: {
    steps: string[];
    time: string;
    difficulty: "Low" | "Medium" | "High";
    ppe: string[];
    torque: string;
  };
  safety: { loto: string[]; hazards: string[]; equipment: string[] };
  parts: { name: string; ref: string; stock: number }[];
  documents: { name: string; type: string; size: string }[];
  history: { date: string; tech: string; parts: string; notes: string }[];
}

export const components: Record<string, Component> = {
  casing: {
    id: "casing",
    name: "Pump Casing",
    status: "healthy",
    function: "Contains and directs fluid flow through the pump.",
    description: "Volute-type casing engineered to convert kinetic energy into pressure head.",
    principle: "Diffuses high-velocity fluid from impeller into discharge pressure.",
    material: "Cast iron ASTM A48 Class 30",
    dimensions: "Ø 420mm × 380mm",
    manufacturer: "KSB / Sulzer",
    lifeExpectancy: "25 years",
    failureModes: ["Erosion", "Corrosion pitting", "Cracks from thermal shock"],
    symptoms: ["External leakage", "Loss of pressure", "Visible corrosion"],
    causes: ["Cavitation damage", "Abrasive slurry", "Improper gasket seating"],
    inspection: {
      checklist: ["Visual inspection", "Wall thickness UT", "Hydrostatic test"],
      tools: ["Ultrasonic gauge", "Borescope", "Torque wrench"],
      tolerances: "Min wall thickness: 8mm",
    },
    maintenance: {
      steps: ["Isolate & drain", "Remove suction/discharge bolts", "Lift casing", "Inspect internals", "Reassemble with new gasket", "Torque to spec"],
      time: "4h",
      difficulty: "Medium",
      ppe: ["Gloves", "Safety glasses", "Steel-toe boots"],
      torque: "M20 → 380 Nm",
    },
    safety: {
      loto: ["Lock main breaker", "Tag with LOTO card", "Verify zero energy"],
      hazards: ["Residual pressure", "Hot surfaces", "Heavy lift"],
      equipment: ["Overhead crane", "Slings", "LOTO kit"],
    },
    parts: [
      { name: "Casing gasket", ref: "GSK-420", stock: 6 },
      { name: "Casing bolts M20", ref: "BLT-M20", stock: 24 },
    ],
    documents: [
      { name: "Casing_Manual.pdf", type: "Manual", size: "2.4 MB" },
      { name: "Casing_Drawing.dwg", type: "Drawing", size: "1.1 MB" },
    ],
    history: [
      { date: "2025-11-04", tech: "M. Bennani", parts: "Gasket", notes: "Replaced due to minor leak." },
    ],
  },
  impeller: {
    id: "impeller",
    name: "Impeller",
    status: "warning",
    function: "Transfers rotational energy from the shaft to the fluid.",
    description: "Closed-type impeller with 6 backward-curved vanes.",
    principle: "Centrifugal acceleration of fluid via rotating vanes.",
    material: "Duplex stainless steel 2205",
    dimensions: "Ø 320mm, 6 vanes",
    manufacturer: "Sulzer",
    lifeExpectancy: "8 years",
    failureModes: ["Cavitation pitting", "Vane erosion", "Imbalance"],
    symptoms: ["Vibration ↑", "Reduced head", "Noise at suction"],
    causes: ["Low NPSH", "Solids in fluid", "Corrosive media"],
    inspection: {
      checklist: ["Check vane surface", "Measure eye diameter", "Balance test"],
      tools: ["Micrometer", "Balancing machine"],
      tolerances: "Balance grade G2.5",
    },
    maintenance: {
      steps: ["LOTO", "Remove casing", "Extract impeller nut", "Puller extraction", "Inspect & balance", "Reinstall with keyed shaft", "Torque impeller nut"],
      time: "3h",
      difficulty: "High",
      ppe: ["Gloves", "Goggles", "Ear protection"],
      torque: "Impeller nut → 220 Nm",
    },
    safety: {
      loto: ["Isolate motor", "Bleed pressure", "Rotate shaft to confirm zero energy"],
      hazards: ["Sharp vanes", "Chemical residue", "Rotating parts"],
      equipment: ["Puller tool", "Chemical-resistant gloves"],
    },
    parts: [
      { name: "Impeller key", ref: "KEY-320", stock: 12 },
      { name: "Impeller nut", ref: "NUT-M24", stock: 8 },
    ],
    documents: [
      { name: "Impeller_Datasheet.pdf", type: "Datasheet", size: "890 KB" },
      { name: "Impeller_SOP.pdf", type: "SOP", size: "1.2 MB" },
    ],
    history: [
      { date: "2025-08-12", tech: "R. Alaoui", parts: "Rebalanced", notes: "Vibration reduced from 8 to 2 mm/s." },
    ],
  },
  shaft: {
    id: "shaft",
    name: "Shaft",
    status: "healthy",
    function: "Transmits torque from motor to impeller.",
    description: "Precision-ground stepped shaft with keyways.",
    principle: "Rigid rotating element transferring mechanical power.",
    material: "AISI 4140 steel, hardened",
    dimensions: "Ø 45mm × 620mm",
    manufacturer: "OEM",
    lifeExpectancy: "15 years",
    failureModes: ["Fatigue crack", "Bending", "Fretting"],
    symptoms: ["Runout > tolerance", "Vibration spikes", "Seal wear"],
    causes: ["Misalignment", "Overload", "Water hammer"],
    inspection: {
      checklist: ["Dial-indicator runout", "MPI crack test", "Straightness check"],
      tools: ["Dial gauge", "MPI kit", "V-blocks"],
      tolerances: "Runout ≤ 0.03mm",
    },
    maintenance: {
      steps: ["Full disassembly", "Clean journals", "Inspect keyways", "MPI", "Reinstall with alignment"],
      time: "6h",
      difficulty: "High",
      ppe: ["Gloves", "Goggles"],
      torque: "N/A",
    },
    safety: {
      loto: ["Full LOTO", "Verify no rotation"],
      hazards: ["Heavy component", "Pinch points"],
      equipment: ["Crane", "Alignment laser"],
    },
    parts: [{ name: "Shaft sleeve", ref: "SLV-045", stock: 4 }],
    documents: [{ name: "Shaft_Drawing.pdf", type: "Drawing", size: "540 KB" }],
    history: [],
  },
  bearingDE: {
    id: "bearingDE",
    name: "Drive-End Bearing",
    status: "healthy",
    function: "Supports radial and axial loads at the coupling end.",
    description: "Deep groove ball bearing, greased for life.",
    principle: "Rolling elements between inner and outer races reduce friction.",
    material: "Chromium steel SKF 6309",
    dimensions: "45 × 100 × 25 mm",
    manufacturer: "SKF",
    lifeExpectancy: "40,000 hrs",
    failureModes: ["Spalling", "Overheating", "Contamination"],
    symptoms: ["High temp > 80°C", "Whining noise", "Grease leak"],
    causes: ["Over-greasing", "Misalignment", "Water ingress"],
    inspection: {
      checklist: ["Vibration analysis", "Temperature check", "Grease sample"],
      tools: ["IR thermometer", "Vibration analyzer"],
      tolerances: "Temp < 75°C, Vib < 4.5 mm/s",
    },
    maintenance: {
      steps: ["LOTO", "Remove bearing cover", "Extract with puller", "Clean housing", "Install new bearing (induction heater)", "Regrease per schedule"],
      time: "2h",
      difficulty: "Medium",
      ppe: ["Heat-resistant gloves", "Goggles"],
      torque: "Cover bolts → 45 Nm",
    },
    safety: {
      loto: ["Motor isolation", "Zero energy verification"],
      hazards: ["Hot bearing", "Sharp puller"],
      equipment: ["Bearing puller", "Induction heater"],
    },
    parts: [
      { name: "SKF 6309", ref: "SKF-6309", stock: 10 },
      { name: "Grease Mobilith SHC 100", ref: "GRS-SHC100", stock: 20 },
    ],
    documents: [{ name: "Bearing_Manual.pdf", type: "Manual", size: "1.8 MB" }],
    history: [{ date: "2025-06-20", tech: "S. Idrissi", parts: "SKF 6309", notes: "Scheduled replacement." }],
  },
  bearingNDE: {
    id: "bearingNDE",
    name: "Non-Drive-End Bearing",
    status: "warning",
    function: "Supports the free end of the shaft opposite the coupling.",
    description: "Angular contact bearing pair, back-to-back.",
    principle: "Handles combined radial and axial thrust loads.",
    material: "Chromium steel SKF 7309 BECBP",
    dimensions: "45 × 100 × 25 mm",
    manufacturer: "SKF",
    lifeExpectancy: "35,000 hrs",
    failureModes: ["Thrust wear", "False brinelling", "Lube starvation"],
    symptoms: ["Axial play", "Rumbling noise", "Temp rise"],
    causes: ["Excessive thrust", "Wrong preload", "Contamination"],
    inspection: {
      checklist: ["Axial play measurement", "Vibration FFT", "Lube analysis"],
      tools: ["Dial gauge", "Vibration analyzer"],
      tolerances: "Axial play ≤ 0.05mm",
    },
    maintenance: {
      steps: ["LOTO", "Remove NDE cover", "Extract paired bearings", "Install new pair with correct orientation", "Set preload", "Regrease"],
      time: "2.5h",
      difficulty: "High",
      ppe: ["Gloves", "Goggles"],
      torque: "Cover bolts → 45 Nm",
    },
    safety: {
      loto: ["Motor lockout", "Cool down period"],
      hazards: ["Hot components", "Precision handling"],
      equipment: ["Puller", "Torque wrench"],
    },
    parts: [{ name: "SKF 7309 BECBP", ref: "SKF-7309", stock: 4 }],
    documents: [{ name: "Angular_Contact_SOP.pdf", type: "SOP", size: "950 KB" }],
    history: [{ date: "2025-10-01", tech: "M. Bennani", parts: "Inspection", notes: "Axial play 0.04mm — within limits, monitor." }],
  },
  seal: {
    id: "seal",
    name: "Mechanical Seal",
    status: "critical",
    function: "Prevents fluid leakage along the rotating shaft.",
    description: "Single cartridge seal, balanced, API Plan 11 flush.",
    principle: "Spring-loaded stationary and rotating faces maintain a thin fluid film to seal the shaft.",
    material: "Silicon carbide / Carbon graphite / Viton",
    dimensions: "Ø 45mm shaft seal",
    manufacturer: "John Crane Type 5860",
    lifeExpectancy: "18,000 hrs",
    failureModes: ["Face wear", "Elastomer swelling", "Blistering", "Dry running"],
    symptoms: ["Visible drip leakage", "Squealing noise", "Steam plume"],
    causes: ["Loss of flush", "Abrasives in fluid", "Thermal shock", "Misalignment"],
    inspection: {
      checklist: ["Check flush flow", "Inspect drain for leakage", "Measure face flatness"],
      tools: ["Flow meter", "Optical flat"],
      tolerances: "Face flatness ≤ 3 helium light bands",
    },
    maintenance: {
      steps: [
        "Execute full LOTO",
        "Drain casing & flush lines",
        "Remove coupling guard and coupling",
        "Remove gland bolts",
        "Slide cartridge seal off shaft",
        "Inspect shaft sleeve for scoring",
        "Install new cartridge with setting clips",
        "Torque gland bolts in star pattern",
        "Remove setting clips before startup",
        "Restore flush and pressurize",
      ],
      time: "3.5h",
      difficulty: "High",
      ppe: ["Chemical gloves", "Face shield", "Apron"],
      torque: "Gland bolts M12 → 65 Nm",
    },
    safety: {
      loto: ["Motor breaker locked", "Suction & discharge valves isolated & tagged", "Flush line depressurized"],
      hazards: ["Process fluid exposure", "Spring energy", "Sharp seal faces"],
      equipment: ["Chemical suit", "Eye wash station nearby", "LOTO kit"],
    },
    parts: [
      { name: "John Crane 5860 cartridge", ref: "JC-5860-045", stock: 2 },
      { name: "Gland gasket", ref: "GSK-GLD", stock: 8 },
      { name: "Shaft sleeve", ref: "SLV-045", stock: 4 },
    ],
    documents: [
      { name: "MechSeal_Manual.pdf", type: "Manual", size: "3.1 MB" },
      { name: "MechSeal_Exploded.pdf", type: "Drawing", size: "1.4 MB" },
      { name: "API682_Plan11.pdf", type: "SOP", size: "780 KB" },
    ],
    history: [
      { date: "2025-11-18", tech: "R. Alaoui", parts: "Faces + O-rings", notes: "Emergency change after leak alarm." },
      { date: "2025-04-02", tech: "S. Idrissi", parts: "Cartridge full", notes: "Scheduled replacement." },
    ],
  },
  wearRing: {
    id: "wearRing",
    name: "Wear Ring",
    status: "healthy",
    function: "Maintains close clearance between impeller and casing to minimize recirculation.",
    description: "Replaceable ring, press-fit into casing.",
    principle: "Sacrificial part protecting impeller and casing from wear.",
    material: "Bronze CuSn12",
    dimensions: "Ø 322mm",
    manufacturer: "OEM",
    lifeExpectancy: "5 years",
    failureModes: ["Clearance growth", "Galling", "Cracking"],
    symptoms: ["Reduced efficiency", "Higher power draw"],
    causes: ["Abrasive wear", "Dry running"],
    inspection: { checklist: ["Measure clearance"], tools: ["Feeler gauge"], tolerances: "Max clearance 0.5mm" },
    maintenance: { steps: ["Remove impeller", "Extract ring", "Press-fit new ring"], time: "2h", difficulty: "Medium", ppe: ["Gloves"], torque: "N/A" },
    safety: { loto: ["Full LOTO"], hazards: ["Press force"], equipment: ["Hydraulic press"] },
    parts: [{ name: "Wear ring bronze", ref: "WR-322", stock: 3 }],
    documents: [{ name: "WearRing_Drawing.pdf", type: "Drawing", size: "320 KB" }],
    history: [],
  },
  coupling: {
    id: "coupling",
    name: "Coupling",
    status: "healthy",
    function: "Connects pump shaft to motor shaft, tolerating minor misalignment.",
    description: "Flexible spacer coupling with elastomeric inserts.",
    principle: "Transmits torque while absorbing vibration and misalignment.",
    material: "Steel hubs, EPDM inserts",
    dimensions: "Bore Ø 45mm",
    manufacturer: "Rexnord Omega",
    lifeExpectancy: "10 years",
    failureModes: ["Insert wear", "Hub crack"],
    symptoms: ["Rubber dust", "Vibration"],
    causes: ["Misalignment", "Overtorque"],
    inspection: { checklist: ["Laser alignment", "Insert visual"], tools: ["Laser aligner"], tolerances: "≤ 0.05mm parallel offset" },
    maintenance: { steps: ["LOTO", "Remove guard", "Replace insert", "Realign"], time: "1.5h", difficulty: "Medium", ppe: ["Gloves"], torque: "Hub bolts → 55 Nm" },
    safety: { loto: ["Motor lockout"], hazards: ["Pinch points"], equipment: ["Laser aligner"] },
    parts: [{ name: "Omega insert", ref: "OMG-E20", stock: 6 }],
    documents: [{ name: "Coupling_Manual.pdf", type: "Manual", size: "1.0 MB" }],
    history: [],
  },
  basePlate: {
    id: "basePlate",
    name: "Base Plate",
    status: "healthy",
    function: "Mounts pump and motor rigidly and dampens vibration.",
    description: "Cast steel skid, grouted to foundation.",
    principle: "Provides rigid common frame for aligned rotating equipment.",
    material: "Steel S275",
    dimensions: "1800 × 700 × 200 mm",
    manufacturer: "OEM",
    lifeExpectancy: "30 years",
    failureModes: ["Corrosion", "Grout crack", "Anchor loosening"],
    symptoms: ["Soft foot", "Increased vibration"],
    causes: ["Foundation settling", "Corrosion"],
    inspection: { checklist: ["Anchor torque", "Grout integrity"], tools: ["Torque wrench"], tolerances: "Levelness ≤ 0.05mm/m" },
    maintenance: { steps: ["Re-torque anchors", "Repair grout if cracked"], time: "2h", difficulty: "Low", ppe: ["Gloves"], torque: "Anchors → 200 Nm" },
    safety: { loto: ["Motor lockout"], hazards: ["Heavy lift"], equipment: ["Torque wrench"] },
    parts: [{ name: "Anchor bolt M24", ref: "ANC-M24", stock: 12 }],
    documents: [{ name: "Baseplate_Drawing.pdf", type: "Drawing", size: "450 KB" }],
    history: [],
  },
  motor: {
    id: "motor",
    name: "Motor",
    status: "healthy",
    function: "Provides rotational power to drive the pump.",
    description: "3-phase induction motor, IE3 efficiency class.",
    principle: "Electromagnetic induction converts electrical to mechanical energy.",
    material: "Cast aluminum frame",
    dimensions: "IEC 180M, 22 kW, 2950 RPM",
    manufacturer: "ABB M3BP",
    lifeExpectancy: "20 years",
    failureModes: ["Winding insulation failure", "Bearing wear", "Overheating"],
    symptoms: ["High current draw", "Trip on thermal", "Smell of burning"],
    causes: ["Overload", "Voltage imbalance", "Poor cooling"],
    inspection: { checklist: ["IR test", "Current balance", "Fan cover clean"], tools: ["Megger", "Clamp meter"], tolerances: "IR ≥ 100 MΩ" },
    maintenance: { steps: ["LOTO", "Clean fan cover", "Check terminal box", "Meg test", "Regrease bearings"], time: "2h", difficulty: "Medium", ppe: ["Electrical gloves", "Arc-flash PPE"], torque: "Terminal lugs → 12 Nm" },
    safety: { loto: ["Breaker off", "Test dead"], hazards: ["Electrical shock", "Arc flash"], equipment: ["Arc-flash suit", "Megger"] },
    parts: [{ name: "Motor bearing 6309", ref: "SKF-6309", stock: 10 }],
    documents: [{ name: "Motor_Datasheet.pdf", type: "Datasheet", size: "1.5 MB" }],
    history: [],
  },
  dischargeFlange: {
    id: "dischargeFlange",
    name: "Discharge Flange",
    status: "healthy",
    function: "Outlet connection to the discharge pipeline.",
    description: "ANSI Class 300 raised-face flange.",
    principle: "Bolted flanged joint sealed with gasket.",
    material: "Carbon steel A105",
    dimensions: "DN100, PN50",
    manufacturer: "OEM",
    lifeExpectancy: "25 years",
    failureModes: ["Gasket leak", "Bolt corrosion"],
    symptoms: ["Weeping at joint"],
    causes: ["Under-torqued bolts", "Old gasket"],
    inspection: { checklist: ["Bolt torque", "Gasket visual"], tools: ["Torque wrench"], tolerances: "As per ASME B16.5" },
    maintenance: { steps: ["Depressurize", "Loosen in star pattern", "Replace gasket", "Retorque"], time: "1h", difficulty: "Low", ppe: ["Gloves"], torque: "M20 → 380 Nm" },
    safety: { loto: ["Isolate & drain"], hazards: ["Stored pressure"], equipment: ["Torque wrench"] },
    parts: [{ name: "Spiral wound gasket DN100", ref: "GSK-SW100", stock: 10 }],
    documents: [{ name: "Flange_Spec.pdf", type: "Datasheet", size: "220 KB" }],
    history: [],
  },
  suctionFlange: {
    id: "suctionFlange",
    name: "Suction Flange",
    status: "healthy",
    function: "Inlet connection from the suction pipeline.",
    description: "ANSI Class 150 raised-face flange, larger bore.",
    principle: "Bolted flanged joint sealed with gasket.",
    material: "Carbon steel A105",
    dimensions: "DN150, PN20",
    manufacturer: "OEM",
    lifeExpectancy: "25 years",
    failureModes: ["Gasket leak", "Cavitation erosion at inlet"],
    symptoms: ["Air ingress", "Noise", "Loss of prime"],
    causes: ["Under-torque", "Vacuum leaks"],
    inspection: { checklist: ["Bolt torque", "Leak test", "Suction pressure"], tools: ["Torque wrench", "Vacuum gauge"], tolerances: "As per ASME B16.5" },
    maintenance: { steps: ["Depressurize", "Replace gasket", "Retorque star pattern"], time: "1h", difficulty: "Low", ppe: ["Gloves"], torque: "M20 → 300 Nm" },
    safety: { loto: ["Isolate suction valve"], hazards: ["Residual fluid"], equipment: ["Torque wrench"] },
    parts: [{ name: "Spiral wound gasket DN150", ref: "GSK-SW150", stock: 8 }],
    documents: [{ name: "Flange_Spec.pdf", type: "Datasheet", size: "220 KB" }],
    history: [],
  },
};

export const componentList = Object.values(components);
